---
version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file printRpiTableHandler.yaml --s3-bucket nepreprpi-src --output-template-file printRpiTableHandlerOut.yaml
      - aws cloudformation package --template-file printTeamTableHandler.yaml --s3-bucket nepreprpi-src --output-template-file printTeamTableHandlerOut.yaml
      - aws cloudformation package --template-file addGameHandler.yaml --s3-bucket nepreprpi-src --output-template-file addGameHandlerOut.yaml

artifacts:
  type: zip
  files:
    - printRpiTableHandlerOut.yaml
    - printTeamTableHandlerOut.yaml
    - addGameHandlerOut.yaml
