---
version: 0.1
phases:
  install:
    commands:
#      - aws cloudformation package --template-file printRpiTableHandler/printRpiTableHandler.yaml --s3-bucket nepreprpi-src --output-template-file printRpiTableHandler/printRpiTableHandlerOut.yaml

artifacts:
  type: zip
  files:
#    - printRpiTableHandler/printRpiTableHandlerOut.yaml
