---
version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --region us-west-2 --template-file printRpiTableHandler/printRpiTableHandler.yaml --s3-bucket nepreprpi-src --output-template-file printRpiTableHandler/printRpiTableHandlerOut.yaml

artifacts:
  type: zip
  files:
    - printRpiTableHandler/printRpiTableHandlerOut.yaml
