---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Cloudformation stack for ECS application'
Resources:
  Method:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      
    
