AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Handler to add games
Resources:
  addGameHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.addGameHandler
      Runtime: python2.7
      CodeUri: lambda/addGameHandler
      Description: Handler to add games
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::530317771161:role/RPITableWrite'
