AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Print team table
Resources:
  printTeamTableHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.printTeamTableHandler
      Runtime: python2.7
      Description: Print team table
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::530317771161:role/service-role/RPITable'
